sudo: false
language: node_js
node_js:
  - 0.10

env:
  matrix:
    - BROWSER=chrome  BVER=stable
    - BROWSER=chrome  BVER=beta
    - BROWSER=chrome  BVER=unstable
    # TODO: Enable more browsers when it runs successfully.
    # - BROWSER=firefox BVER=stable
    # - BROWSER=firefox BVER=beta
    # - BROWSER=firefox BVER=unstable
    # - BROWSER=firefox BVER=esr

matrix:
  fast_finish: true

  allow_failures:
    - env: BROWSER=chrome  BVER=unstable
    # - env: BROWSER=firefox BVER=unstable

before_script:
  - npm install
  - bower update
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - grunt
  - npm test
