application: test-rtc
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /manual/
  static_files: src/manual/index.html
  upload: src/manual/index.html

- url: /manual/(.+)/
  static_files: src/manual/\1/index.html
  upload: src/manual/(.+)/index.html

- url: /manual
  static_dir: src/manual

- url: /images
  static_files: src/images
  upload: src/images

- url: /js
  static_dir: src/js

- url: /css
  static_dir: src/css

- url: /components/testrtc/ui
  static_dir: src/ui

- url: /components
  static_dir: components

- url: /.*
  script: testrtc.app
  secure: always

libraries:
- name: jinja2
  version: latest
