application: test-rtc
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /manual
  static_dir: src/manual

- url: /js
  static_dir: src/js

- url: /css
  static_dir: src/css

- url: /bower_components/testrtc/ui
  static_dir: src/ui

- url: /bower_components
  static_dir: bower_components

- url: /.*
  script: testrtc.app
  secure: always

libraries:
- name: jinja2
  version: latest
